### PR TITLE
Device template tasks were using wrong ansible variables for authentication

### PR DESCRIPTION
**Pull request by radtrentasei**
With this fix we are changing the way device template tasks leverage ansible variables.

### CODE REVIEW

**Comment by stevenca** [comment]
Can one of the admins verify this patch?

**Comment by radtrentasei** [comment]
run tests

**Comment by jasonking3** [comment]
run tests

**Comment by jasonking3** [comment]
run tests

**Comment by jasonking3** [comment]
run tests

**Comment by jasonking3** [comment]
ok to test

**Pull request merged**
